// sample-angular-web-app/src/app/components/video-chat/video-chat.component.ts
import { ChangeDetectorRef, Component, ElementRef, Input, ViewChild } from '@angular/core';
import { WebRTCService } from '../../../../projects/ts-webrtc-angular-client/src/public-api';
import { FileTransferResult } from '../../../../projects/ts-webrtc-angular-client/src/lib/models';

@Component({
  selector: 'app-video-chat',
  imports: [],
  templateUrl: './video-chat.component.html',
  styleUrl: './video-chat.component.css',
  standalone: true,
  providers: [WebRTCService]
})
export class VideoChatComponent {
  
  public _inviteSent: boolean = false;
  public _inviteAccepted: boolean = false;
  public _roomId: string = "";
  public _isMute: boolean = false;
  public _isVideoStopped: boolean = false;

  public _callStarted: boolean = false;
  public _callEnded: boolean = false;
  public _errorMessage: string = "";
  public _showError: boolean = false;

  public _disableStartCall: boolean = true;

  public _isScreenShare: boolean = false;

  constructor(private videoChatService:WebRTCService, private cdr: ChangeDetectorRef) { }
  
  @Input() myUserType: UserType = UserType.Local;

  @ViewChild('localChat') localChat!: ElementRef;
  @ViewChild('remoteChat') remoteChat!: ElementRef;

  public get userType(): typeof UserType {
    return UserType; 
  }

  ngOnInit(): void {    
    if (this.myUserType == UserType.Remote) {
      this.videoChatService.onInvite.subscribe( async (roomId:string) => {
        console.log("Invite received in component. Room id:", roomId);
        this._roomId = roomId;

        console.log("Component: Starting call as remote user.");
        await this.videoChatService.remoteStartCallAsync();
        this._callStarted = true;
        this.cdr.detectChanges();

        await this.videoChatService.acceptInviteAsync(roomId);        
      });
    }
    if (this.myUserType == UserType.Local) {
      this.videoChatService.onInviteAccepted.subscribe( async () => {
        console.log("Invite accepted event received in component.");
        
        this._inviteAccepted = true;
        this._disableStartCall = false;

        this.cdr.detectChanges();
      });
    }
    this.videoChatService.onToggleAudio.subscribe( (isMute:boolean) => {
      console.log("ToggleMute event received in component. isMute:", isMute);
      this._isMute = isMute;
      this.cdr.detectChanges();
    });
    this.videoChatService.onToggleVideo.subscribe( (isVideoStopped:boolean) => {
      console.log("ToggleVideo event received in component. isVideoStopped:", isVideoStopped);
      this._isVideoStopped = isVideoStopped;
      this.cdr.detectChanges();
    });
    this.videoChatService.onChatMessage.subscribe( (message:string) => {
      console.log("ChatMessage event received in component. message:", message);
      this.remoteChat.nativeElement.textContent = message
      this.cdr.detectChanges();
    });
    this.videoChatService.onFileTransfer.subscribe( (result:FileTransferResult) => {
      console.log("FileTransfer event received in component. result.name:", result.name);
      (window as any).downloadFileFromByteArray(result.name!, result.type!, this.base64ToUint8Array(result.data!));
      this.cdr.detectChanges();
    });
  }

  ngAfterViewInit(): void {
    //this.videoChatService.setSettings("localUniqueUserId", "remoteUniqueUserId");
    this.videoChatService.setHubUrl("https://localhost:7298/chathub");
    const localVideo = document.getElementById("localVideo") as HTMLVideoElement;
    const remoteVideo = document.getElementById("remoteVideo") as HTMLVideoElement;
    this.videoChatService.setVideos(localVideo, remoteVideo);

    (async () => {
      console.log("Component: Starting hub connection.");
      await this.videoChatService.startHubConnectionAsync();
    })(); 
  }

  async invite(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";
      this._inviteSent = false;
      await this.videoChatService.inviteAsync();
      this._inviteSent = true;
    }
    catch (err:any) {
      console.error("Error in invite:", err);
      this._errorMessage = err?.message ?? "Error in invite.";
      this._showError = true;
      this._inviteSent = false;
    }
  }

  async inviteAll(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";
      this._inviteSent = false;
      await this.videoChatService.inviteAllAsync();
      this._inviteSent = true;
    }
    catch (err:any) {
      console.error("Error in inviteAll:", err);
      this._errorMessage = err?.message ?? "Error in inviteAll.";
      this._showError = true;
      this._inviteSent = false;
    }
  }

  async startCall(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";
      this._callStarted = false;
      // Start local media (screen sharing)
      //await this.videoChatService.startLocalScreenMediaAsync();      
      await this.videoChatService.startCallAsync();
      this._callStarted = true;
      this._disableStartCall = true;
    }
    catch (err:any) {
      console.error("Error in startCall:", err);
      this._errorMessage = err?.message ?? "Error in startCall.";
      this._showError = true;
      this._callStarted = false;
    }
  }

  async sendMessage(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";   
      await this.videoChatService.sendChatMessageAsync(this.localChat.nativeElement.value);
    }
    catch (err:any) {
      console.error("Error in sendMessage:", err);
      this._errorMessage = err?.message ?? "Error in sendMessage.";
      this._showError = true;
    }
  }

  async switchMe(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";
      this._callStarted = false; 
      
      if (this._isScreenShare) {
        await this.videoChatService.switchScreenShareToVideoAsync();
        this._isScreenShare = false;
      }
      else {
        await this.videoChatService.switchVideoToScreenShareAsync();
        this._isScreenShare = true;
      }

      this._callStarted = true;
      this._disableStartCall = true;
    }
    catch (err:any) {
      console.error("Error in startCall:", err);
      this._errorMessage = err?.message ?? "Error in startCall.";
      this._showError = true;
      this._callStarted = false;
    }
  }

  async toggleAudio(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";
      await this.videoChatService.toggleAudioAsync();
    }
    catch (err:any) {
      console.error("Error in toggleAudio:", err);
      this._errorMessage = err?.message ?? "Error in toggleAudio.";
      this._showError = true;
    }
  }

  async toggleVideo(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";
      await this.videoChatService.toggleVideoAsync();
    }
    catch (err:any) {
      console.error("Error in toggleVideo:", err);
      this._errorMessage = err?.message ?? "Error in toggleVideo.";
      this._showError = true;
    }
  }

  async endCall(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";
      await this.videoChatService.endCallAsync();
    }
    catch (err:any) {
      console.error("Error in endCall:", err);
      this._errorMessage = err?.message ?? "Error in endCall.";
      this._showError = true;
    }
  }

  async onFileSelected(event: Event): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";

      const input = event.target as HTMLInputElement;

      if (input.files && input.files.length > 0) {
        for (let i=0; i<input.files.length; i++)
        {
          var file:File = input.files[i];
          var b = new Blob([file], {type: file.type});
          var arr = new Uint8Array(await b.arrayBuffer());
          await this.videoChatService.transferFileAsync(arr, file.name, file.type);
        }
      }      
    }
    catch (err:any) {
      console.error("Error in onFileSelected:", err);
      this._errorMessage = err?.message ?? "Error in onFileSelected.";
      this._showError = true;
    }    
  }
  
  base64ToUint8Array(base64String: string): Uint8Array {
    try {
      // Decode the Base64 string into a raw string
      const rawString = atob(base64String);
  
      // Create a Uint8Array with the same length as the raw string
      const uint8Array = new Uint8Array(rawString.length);
  
      // Populate the Uint8Array with the character codes of the raw string
      for (let i = 0; i < rawString.length; i++) {
        uint8Array[i] = rawString.charCodeAt(i);
      }
  
      return uint8Array;
    } catch (error) {
      console.error('Error converting Base64 to Uint8Array:', error);
      throw new Error('Invalid Base64 string');
    }
  }
}

export enum UserType
{
    Local,
    Remote
} 

@if(_showError){
    <div class="row">
        <div class="col-12" style="margin-left: 5px;">
            <span style="background-color: red; color: white;">Error: {{_errorMessage}}</span>
        </div>
    </div>
}
<div class="container">
    <div id="video-grid">
        <video class="overlay" id="localVideo" autoplay muted>
        </video>
        <video class="background" id="remoteVideo" autoplay>
        </video>
    </div>
</div>    

@if(_callStarted) {
    <br />
    <div class="row">
        <div class="col-12" style="margin-left: 5px;">
            <input type="file" (change)="onFileSelected($event)" />
        </div>
    </div>
}

@if(_callStarted) {
    <div class="row">
        <div class="col-12" style="margin-left: 5px;">
            <textarea rows="5" #localChat style="width:400px;">
            </textarea>
        </div>            
    </div>
    <div class="row">
        <div class="col-12" style="margin-left: 5px; width:400px;">
            <button style="width: 400px;" [disabled]="!_callStarted" (click)="sendMessage()">Send Message</button>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-12" style="margin-left: 5px;">
            <textarea rows="5" #remoteChat style="width:400px;">
            </textarea>
        </div>
    </div>
    <br />
}

@if (_inviteAccepted) {
    <br />
    <div class="row">
        <div class="col-12" style="margin-left: 5px;">
            <span style="background-color: green; color: white;">Invite accepted.</span>
        </div>
    </div>
}
@if (this.myUserType == userType.Local)
{
    <div class="row" style="margin-top: 10px; margin-left: 5px;">
        <div class="col-lg-4 col-md-4 col-sm-12">
            <button [disabled]="_inviteSent" style="width: 90%;" (click)="inviteAll()">Invite</button>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <button [disabled]="_disableStartCall" style="width: 90%;" (click)="startCall()">Start Call</button>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <button [disabled]="!_callStarted" style="width: 90%;" (click)="switchMe()">{{_isScreenShare ? "To Video" : "To Screen"}}</button>
        </div>        
    </div>
    <div class="row" style="margin-top: 10px; margin-left: 5px;">
        <div class="col-lg-4 col-md-4 col-sm-12">
            <button [disabled]="!_callStarted" style="width: 90%;" (click)="toggleAudio()">{{_isMute ? "Unmute" : "Mute"}}</button>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <button [disabled]="!_callStarted || _isScreenShare" style="width: 90%;" (click)="toggleVideo()">{{_isVideoStopped ? "Start Video" : "Stop Video"}}</button>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <button [disabled]="!_callStarted" style="width: 90%;" (click)="endCall()">End Call</button>
        </div>
    </div>
}
@else 
{
    <div class="row" style="margin-top: 10px; margin-left: 5px;">
        <div class="col-lg-4 col-md-4 col-sm-12">
            <button [disabled]="!_callStarted" style="width: 90%;" (click)="toggleAudio()">{{_isMute ? "Unmute" : "Mute"}}</button>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <button [disabled]="!_callStarted" style="width: 90%;" (click)="toggleVideo()">{{_isVideoStopped ? "Start Video" : "Stop Video"}}</button>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
            <button (click)="endCall()" style="width: 90%;">End Call</button>
        </div>
    </div>
}

// sample-react-web-app/src/components/VideoChat.tsx
import React, { useEffect, useState } from 'react';
import { VideoChatProps, UserType } from './VideoChat.Models';
import './VideoChat.css';
import { FileTransferResult } from 'ts-webrtc-react-client'

const VideoChat: React.FC<VideoChatProps> = ({ videoChatService, userType }) => {
    
  const [_inviteSent, setInviteSent] = useState<boolean>(false);
  const [_inviteAccepted, setInviteAccepted] = useState<boolean>(false);
  const [_roomId, setRoomId] = useState<string>("");

  const [_callStarted, setCallStarted] = useState<boolean>(false);
  const [_callEnded, setCallEnded] = useState<boolean>(false);
  const [_errorMessage, setErrorMessage] = useState<string>("");
  const [_showError, setShowError] = useState<boolean>(false);

  const [_disableStartCall, setDisableStartCall] = useState<boolean>(true);
  const [_isMute, setIsMute] = useState<boolean>(false);
  const [_isVideoStopped, setIsVideoStopped] = useState<boolean>(false);

  const [_isScreenShare, setIsScreenShare] = useState<boolean>(false);

  const [_localChat, setLocalChat] = useState<string>("");
  const [_remoteChat, setRemoteChat] = useState<string>("");

  const  handleInviteAccepted = async () => {
        console.log("handleInviteAccepted: Invite accepted.");
        setInviteAccepted(true);
        setDisableStartCall(false);
        setShowError(false);
    };

  const handleInvite = async (e: any) => {
        if (!videoChatService) return;
        console.log("handleInvite: Received invite for roomId: ", e.detail);

        await videoChatService.remoteStartCallAsync();
        setCallStarted(true);

        await videoChatService.acceptInviteAsync(e.detail);
        setRoomId(e.detail);
        setInviteSent(true);
        setShowError(false);
    };

  const toggleAudio = async (e: any) => {
        console.log("toggleAudio: isMute: ", e.detail);
        setIsMute(e.detail);     
    };

  const toggleVideo = async (e: any) => {
        console.log("toggleVideo: isVideoStopped: ", e.detail);
        setIsVideoStopped(e.detail);     
    };

    const chatMessage = async (e: any) => {
        console.log("ChatMessage event received in component. e:", e);
        setRemoteChat(e.detail);
    }

    const fileTransfer = async (e: any) => {
        console.log("FileTransfer event received in component. result:", e);
        var file = e.detail as FileTransferResult;
        (window as any).downloadFileFromByteArray(file.name!, file.type!, base64ToUint8Array(file.data!));     
    };

    const handleChange = (e: any) => {
        // Update the 'text' state with the new value from the textarea.
        setLocalChat(e.target.value);
    };

    useEffect(() => {
        // Cleanup event listeners on unmount
        return () => {
            if (userType === UserType.Remote) { 
                window.removeEventListener("onInvite", handleInvite);
            }
            else {
                window.removeEventListener("onInviteAccepted", handleInviteAccepted);
            }
            window.removeEventListener("onToggleAudio", toggleAudio);
            window.removeEventListener("onToggleVideo", toggleVideo);
            window.removeEventListener("onChatMessage", chatMessage);
            window.removeEventListener("onFileTransfer", fileTransfer);
        };
    }, [videoChatService]);

    // useEffect(() => {
    //     console.log("Local chat updated:", _localChat);

    //     const localChatUpdated = async () => {
    //         if (videoChatService) {
    //             try {
    //                 setShowError(false);
    //                 await videoChatService.sendMessageAsync(_localChat);
    //             } catch (error: any) {
    //                 setErrorMessage(error.message);
    //                 setShowError(true);
    //             }
    //         }
    //     };

    //     localChatUpdated();

    // }, [_localChat]);

    useEffect(() => {
        const initializeVideoChat = async () => {
            if (videoChatService) {
                videoChatService.setHubUrl("https://localhost:7298/chathub");
                const localVideo = document.getElementById("localVideo") as HTMLVideoElement;
                const remoteVideo = document.getElementById("remoteVideo") as HTMLVideoElement;
                videoChatService.setVideos(localVideo, remoteVideo);
                
                await videoChatService.startHubConnectionAsync();

                if (userType === UserType.Remote) {
                    window.addEventListener("onInvite", handleInvite);
                }
                else {
                    window.addEventListener("onInviteAccepted", handleInviteAccepted);
                }

                window.addEventListener("onToggleAudio", toggleAudio);
                window.addEventListener("onToggleVideo", toggleVideo);
                window.addEventListener("onChatMessage", chatMessage);
                window.addEventListener("onFileTransfer", fileTransfer);
            }
        };        

        initializeVideoChat();
    }, [videoChatService]);

    const MyErrorMessage: React.FC<{ show: boolean }> = ({ show }) => {
        if (!show) return null;
        return (
            <div className="row">
                <div className="col-12" style={{marginLeft: 5}}>
                    <span style={{backgroundColor: 'red', color: 'white'}}>Error: {_errorMessage}</span>
                </div>
            </div>
        );
    };

    const Chat: React.FC<{ show: boolean }> = ({ show }) => {
        if (!show) return null;
        return (
            <div>
                <form>
                    <div className="row">
                        <div className="col-12" style={{marginLeft: 5}}>
                            <textarea id="localChat" rows={parseInt("5")} style={{width:400}} onChange={handleChange} value={_localChat}>
                            </textarea>                        
                        </div>                           
                    </div>
                    <div className="row">
                        <div className="col-12" style={{marginLeft: 5}}>
                            <button type='button' style={{width: 400}} onClick={async () => await sendMessage()}>Send Message</button>
                        </div>                           
                    </div>
                </form>                
                <br />
                <div className="row">
                    <div className="col-12" style={{marginLeft: 5}}>
                        <textarea id="remoteChat" rows={parseInt("5")} style={{width:400}} value={_remoteChat} readOnly>
                        </textarea>
                    </div>
                </div>
                <br />
            </div>            
        );
    };

    const InviteAccepted: React.FC<{ show: boolean }> = ({ show }) => {
        if (!show) return null;
        return (
            <div className="row">
                <div className="col-12" style={{marginLeft: 5}}>
                    <span style={{backgroundColor: 'green', color: 'white'}}>Invite accepted.</span>
                </div>
            </div>
        );
    };

    const FileTransferPanel: React.FC<{ show: boolean }> = ({ show }) => {
        if (!show) return null;
        return (
            <div className="row">
                <div className="col-12" style={{ marginLeft: 5}}>
                    <input type="file" onChange={async (e) => await onFileSelected(e)} />
                </div>
            </div>
        );
    };    

    const LocalButtonPanel: React.FC<{ show: boolean }> = ({ show }) => {
        if (!show) return null;
        return (
            <div style={{marginTop: 10, width: "100%"}}>
                <div className="row" style={{marginTop: 10, marginLeft: 5}}>
                    <div className="col-lg-4 col-md-4 col-sm-12">
                        <button disabled={_inviteSent} style={{width: "90%"}} onClick={() => inviteAll()}>Invite</button>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12">
                        <button disabled={_disableStartCall} style={{width: "90%"}} onClick={() => startCall()}>Start Call</button>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12">
                        <button disabled={!_callStarted} style={{width: "90%"}} onClick={() => switchMe()}>{_isScreenShare ? "To Video" : "To Screen"}</button>
                    </div>                    
                </div>
                <div className="row" style={{marginTop: 10, marginLeft: 5}}>
                    <div className="col-lg-4 col-md-4 col-sm-12">
                        <button disabled={!_callStarted} style={{width: "90%"}} onClick={async () => await toggleAudioAsync()}>{!_isMute ? "Mute" : "Unmute"}</button>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12">
                        <button disabled={!_callStarted || _isScreenShare} style={{width: "90%"}} onClick={async () => await toggleVideoAsync()}>{!_isVideoStopped ? "Stop Video" : "Start Video"}</button>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12">
                        <button disabled={!_callStarted} style={{width: "90%"}} onClick={() => endCall()}>End Call</button>
                    </div>
                </div>
            </div>            
        );
    };

    const RemoteButtonPanel: React.FC<{ show: boolean }> = ({ show }) => {
        if (!show) return null;
        return (
            <div style={{marginTop: 10, width: "100%"}}>
                <div className="row" style={{marginTop: 10, marginLeft: 5}}>
                    <div className="col-lg-4 col-md-4 col-sm-12">
                        <button disabled={!_callStarted} style={{width: "90%"}} onClick={async () => await toggleAudioAsync()}>{!_isMute ? "Mute" : "Unmute"}</button>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12">
                        <button disabled={!_callStarted} style={{width: "90%"}} onClick={async () => await toggleVideoAsync()}>{!_isVideoStopped ? "Stop Video" : "Start Video"}</button>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12">                    
                        <button style={{width: "90%"}} onClick={() => endCall()}>End Call</button>
                    </div>
                </div>
            </div>            
        );
    };

    async function inviteAll() {
        if (videoChatService) {
            try {
                setShowError(false);
                await videoChatService.inviteAllAsync();
                setInviteSent(true);
            } catch (error: any) {
                setErrorMessage(error.message);
                setShowError(true);
                setInviteSent(false);
            }            
        }
    }

    async function startCall() {
        if (videoChatService) {
            try {
                setShowError(false);
                setCallStarted(false);
                setIsScreenShare(false);
                // Start local media (screen sharing)
                //await videoChatService.startLocalScreenMediaAsync();               
                await videoChatService.startCallAsync();
                setCallStarted(true);
                setDisableStartCall(true);
            } catch (error: any) {
                setErrorMessage(error.message);
                setShowError(true);
                setDisableStartCall(false);
                setCallStarted(false);
            }
        }
    }

    async function sendMessage() {
        if (videoChatService) {
            try {
                setShowError(false);
                await videoChatService.sendChatMessageAsync(_localChat);
            } catch (error: any) {
                setErrorMessage(error.message);
                setShowError(true);
            }
        }
    }

    async function switchMe() {
        if (videoChatService) {
            try {
                setShowError(false);
                setCallStarted(false);
                if (_isScreenShare) {
                    await videoChatService.switchScreenShareToVideoAsync();                    
                    setIsScreenShare(false);

                } else {
                    await videoChatService.switchVideoToScreenShareAsync();
                    setIsScreenShare(true);
                }
                setCallStarted(true);
                setDisableStartCall(true);
            } catch (error: any) {
                setErrorMessage(error.message);
                setShowError(true);
                setDisableStartCall(false);
                setCallStarted(false);
            }
        }
    }

    async function toggleAudioAsync() {
        if (videoChatService) {
            try {
                setShowError(false);               
                videoChatService.toggleAudioAsync();
            } catch (error: any) {
                setErrorMessage(error.message);
                setShowError(true);
            }
        }
    }

    async function toggleVideoAsync() {
        if (videoChatService) {
            try {
                setShowError(false);               
                videoChatService.toggleVideoAsync();
            } catch (error: any) {
                setErrorMessage(error.message);
                setShowError(true);
            }
        }
    }

    async function endCall() {
        if (videoChatService) {
            try {
                await videoChatService.endCallAsync();
            } catch (error: any) {
                setErrorMessage(error.message);
                setShowError(true);
            }
            setCallEnded(true);
        }
    }

    async function onFileSelected(e: React.ChangeEvent<HTMLInputElement>): Promise<void> {
        try {
            if (videoChatService) {
                setShowError(false);

                var input = e.target as HTMLInputElement;
            
                if (input.files && input.files.length > 0) {
                    for (let i=0; i<input.files.length; i++)
                    {
                        var file:File = input.files[i];
                        var b = new Blob([file], {type: file.type});
                        var arr = new Uint8Array(await b.arrayBuffer());
                        videoChatService.transferFileAsync(arr, file.name, file.type);
                    }
                }
            }                
        }
        catch (err:any) {
          console.error("Error in onFileSelected:", err);
          setErrorMessage(err?.message ?? "Error in onFileSelected.");
          setShowError(true);
        }    
      }

    function base64ToUint8Array(base64String: string): Uint8Array {
        try {
          // Decode the Base64 string into a raw string
          const rawString = atob(base64String);
      
          // Create a Uint8Array with the same length as the raw string
          const uint8Array = new Uint8Array(rawString.length);
      
          // Populate the Uint8Array with the character codes of the raw string
          for (let i = 0; i < rawString.length; i++) {
            uint8Array[i] = rawString.charCodeAt(i);
          }
      
          return uint8Array;
        } catch (error) {
          console.error('Error converting Base64 to Uint8Array:', error);
          throw new Error('Invalid Base64 string');
        }
    }

    return (
        <div style={{width: "100%", marginTop: 20}}>
            <div style={{marginTop: 10}}>        
                Video Chat Component ({userType === UserType.Local ? "Local" : "Remote"})
            </div>
            
            <MyErrorMessage show={_showError} />

            <div className="container">
                <div id="video-grid">
                    <video className="overlay" id="localVideo" autoPlay muted>
                    </video>
                    <video className="background" id="remoteVideo" autoPlay>
                    </video>
                </div>
            </div>

            <br />
                
            <FileTransferPanel show={_callStarted}/>

            <br />

            <Chat show={_callStarted} />

            <br />

            <InviteAccepted show={_inviteAccepted} />

            <br />

            <LocalButtonPanel show={userType === UserType.Local} />

            <RemoteButtonPanel show={userType === UserType.Remote} />
        </div>
    );
  };

export default VideoChat;
