// sample-angular-web-app/src/video-chat/video-chat.component.ts
import { Component, Input, ViewChild } from '@angular/core';
import { WebRTCService } from '../../projects/ts-webrtc-angular-client/src/public-api';

@Component({
  selector: 'app-video-chat',
  imports: [],
  templateUrl: './video-chat.component.html',
  styleUrl: './video-chat.component.css',
  standalone: true,
  providers: [WebRTCService]
})
export class VideoChatComponent {
  
  public _inviteSent: boolean = false;
  public _inviteAccepted: boolean = false;
  public _roomId: string = "";

  public _callStarted: boolean = false;
  public _callEnded: boolean = false;
  public _errorMessage: string = "";
  public _showError: boolean = false;

  public _disableStartCall: boolean = true; //(!this._inviteAccepted || this._callStarted)

  constructor(private videoChatService:WebRTCService) { }
  
  @Input() myUserType: UserType = UserType.Local;

  @ViewChild('localVideo') localVideo!: HTMLVideoElement;
  @ViewChild('remoteVideo') remoteVideo!: HTMLVideoElement;

  public get userType(): typeof UserType {
    return UserType; 
  }

  ngOnInit(): void {    
    if (this.myUserType == UserType.Remote) {
      this.videoChatService.onInvite.subscribe( async (roomId:string) => {
        console.log("Invite received in component. Room id:", roomId);
        this._roomId = roomId;
        await this.videoChatService.acceptInviteAsync(roomId);        
      });
    }
    if (this.myUserType == UserType.Local) {
      this.videoChatService.onInviteAccepted.subscribe( async () => {
        console.log("Invite accepted event received in component.");
        //await this.videoChatService.startCallAsync();
        this._inviteAccepted = true;
        this._disableStartCall = false;
      });
    }
  }

  ngAfterViewInit(): void {
    //this.videoChatService.setSettings("user1", "user2");

    this.videoChatService.setHubUrl("https://localhost:7298/chathub");
    //this.videoChatService.setSettings("user1", "user2");
    // const localVideo = document.getElementById("localVideo") as HTMLVideoElement;
    // const remoteVideo = document.getElementById("remoteVideo") as HTMLVideoElement;
    this.videoChatService.setVideos(this.localVideo, this.remoteVideo);

    (async () => {
      console.log("Component: Starting hub connection.");
      await this.videoChatService.startHubConnectionAsync();
      if (this.myUserType == UserType.Remote) {
        console.log("Component: Starting call as remote user.");
        await this.videoChatService.remoteStartCallAsync();
      }
    })(); 
  }

  async invite(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";
      await this.videoChatService.inviteAsync();
    }
    catch (err:any) {
      console.error("Error in invite:", err);
      this._errorMessage = err?.message ?? "Error in invite.";
      this._showError = true;
    }
  }

  async inviteAll(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";
      this._inviteSent = false;
      await this.videoChatService.inviteAllAsync();
      this._inviteSent = true;
    }
    catch (err:any) {
      console.error("Error in inviteAll:", err);
      this._errorMessage = err?.message ?? "Error in inviteAll.";
      this._showError = true;
      this._inviteSent = false;
    }
  }

  async startCall(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";
      this._callStarted = false;      
      await this.videoChatService.startCallAsync();
      this._callStarted = true;
      this._disableStartCall = true;
    }
    catch (err:any) {
      console.error("Error in startCall:", err);
      this._errorMessage = err?.message ?? "Error in startCall.";
      this._showError = true;
      this._callStarted = false;
    }
  }

  async endCall(): Promise<void> {
    try {
      this._showError = false;
      this._errorMessage = "";
      await this.videoChatService.endCallAsync();
    }
    catch (err:any) {
      console.error("Error in endCall:", err);
      this._errorMessage = err?.message ?? "Error in endCall.";
      this._showError = true;
    }
  }
}

export enum UserType
{
    Local,
    Remote
} 

<p>video-chat works!</p>

<div>
    @if(_showError){
        <div class="row">
            <div class="col-12" style="margin-left: 5px;">
                <span style="background-color: red; color: white;">Error: {{_errorMessage}}</span>
            </div>
        </div>
    }
    <div id="video-grid">
        <video #localVideo autoplay muted>
        </video>
        <video #remoteVideo autoplay>
        </video>
    </div>
    <br />
    @if (_inviteAccepted) {
        <div class="row">
            <div class="col-12" style="margin-left: 5px;">
                <span style="background-color: green; color: white;">Invite accepted.</span>
            </div>
        </div>
    }
    <div class="row">
        @if (this.myUserType == userType.Local)
        {
            <div class="col-3" style="margin-left: 5px;">
                <button [disabled]="_inviteSent"  (click)="inviteAll()">Invite</button>
            </div>
            <div class="col-3" style="margin-left: 5px;">
                <button [disabled]="_disableStartCall" (click)="startCall()">Start Call</button>
            </div>
            <div class="col-3">
                <button [disabled]="!_callStarted" (click)="endCall()">End Call</button>
            </div>
        }
        @else
        {
            <div class="col-3" style="margin-left: 5px;">
                <button (click)="endCall()">End Call</button>
            </div>
        }        
    </div>
</div>

// sample-react-web-app/src/components/VideoChat.tsx
import React, { useEffect, useState } from 'react';
import { VideoChatProps, UserType } from './VideoChat.Models';

const VideoChat: React.FC<VideoChatProps> = ({ videoChatService, userType }) => {
    
  const [_inviteSent, setInviteSent] = useState<boolean>(false);
  const [_inviteAccepted, setInviteAccepted] = useState<boolean>(false);
  const [_roomId, setRoomId] = useState<string>("");

  const [_callStarted, setCallStarted] = useState<boolean>(false);
  const [_callEnded, setCallEnded] = useState<boolean>(false);
  const [_errorMessage, setErrorMessage] = useState<string>("");
  const [_showError, setShowError] = useState<boolean>(false);

  const [_disableStartCall, setDisableStartCall] = useState<boolean>(true);

  const  handleInviteAccepted = async () => {
        console.log("handleInviteAccepted: Invite accepted.");
        setInviteAccepted(true);
        setDisableStartCall(false);
        setShowError(false);
    };

  const handleInvite = async (e: any) => {
        if (!videoChatService) return;
        console.log("handleInvite: Received invite for roomId: ", e.detail);
        await videoChatService.acceptInviteAsync(e.detail);
        setRoomId(e.detail);
        setInviteSent(true);
        setShowError(false);
    };

    useEffect(() => {
        const initializeVideoChat = async () => {
            if (videoChatService) {
                videoChatService.setHubUrl("https://localhost:7298/chathub");
                const localVideo = document.getElementById("localVideo") as HTMLVideoElement;
                const remoteVideo = document.getElementById("remoteVideo") as HTMLVideoElement;
                videoChatService.setVideos(localVideo, remoteVideo);
                
                await videoChatService.startHubConnectionAsync();

                if (userType === UserType.Remote) {
                    await videoChatService.remoteStartCallAsync();
                    
                    window.addEventListener("onInvite", handleInvite);
                }
                else {
                    window.addEventListener("onInviteAccepted", handleInviteAccepted);
                }
            }
        };        

        initializeVideoChat();
    }, [videoChatService]);

    const MyErrorMessage: React.FC<{ show: boolean }> = ({ show }) => {
        if (!show) return null;
        return (
            <div className="row">
                <div className="col-12" style={{marginLeft: 5}}>
                    <span style={{backgroundColor: 'red', color: 'white'}}>Error: {_errorMessage}</span>
                </div>
            </div>
        );
    };

    const InviteAccepted: React.FC<{ show: boolean }> = ({ show }) => {
        if (!show) return null;
        return (
            <div className="row">
                <div className="col-12" style={{marginLeft: 5}}>
                    <span style={{backgroundColor: 'green', color: 'white'}}>Invite accepted.</span>
                </div>
            </div>
        );
    };

    const LocalButtonPanel: React.FC<{ show: boolean }> = ({ show }) => {
        if (!show) return null;
        return (
            <div className="row">
                <div className="col-3" style={{marginLeft: 5}}>
                    <button disabled={_inviteSent} onClick={() => inviteAll()}>Invite</button>
                </div>
                <div className="col-3">
                    <button disabled={_disableStartCall} onClick={() => startCall()}>Start Call</button>
                </div>
                <div className="col-3">
                    <button disabled={!_callStarted} onClick={() => endCall()}>End Call</button>
                </div>
            </div>
        );
    };

    const RemoteButtonPanel: React.FC<{ show: boolean }> = ({ show }) => {
        if (!show) return null;
        return (
            <div className="row">
                <div className="col-3">
                    <button onClick={() => endCall()}>End Call</button>
                </div>
            </div>
        );
    };

    async function inviteAll() {
        if (videoChatService) {
            try {
                setShowError(false);
                await videoChatService.inviteAllAsync();
                setInviteSent(true);
            } catch (error: any) {
                setErrorMessage(error.message);
                setShowError(true);
                setInviteSent(false);
            }            
        }
    }

    async function startCall() {
        if (videoChatService) {
            try {
                setShowError(false);
                setCallStarted(false);               
                await videoChatService.startCallAsync();
                setCallStarted(true);
                setDisableStartCall(true);
            } catch (error: any) {
                setErrorMessage(error.message);
                setShowError(true);
                setDisableStartCall(false);
                setCallStarted(false);
            }
        }
    }

    async function endCall() {
        if (videoChatService) {
            try {
                await videoChatService.endCallAsync();
            } catch (error: any) {
                setErrorMessage(error.message);
                setShowError(true);
            }
            setCallEnded(true);
        }
    }

    return (
        <div>
            <div>        
                Video Chat Component ({userType === UserType.Local ? "Local" : "Remote"})
            </div>
            
            <MyErrorMessage show={_showError} />
                            
            <div id="video-grid">
                <video id="localVideo" autoPlay muted>
                </video>
                <video id="remoteVideo" autoPlay>
                </video>
            </div>

            <InviteAccepted show={_inviteAccepted} />

            <LocalButtonPanel show={userType === UserType.Local} />

            <RemoteButtonPanel show={userType === UserType.Remote} />
        </div>
    );
  };

export default VideoChat;
